services:
  fastapi:
    build: .
    container_name: fastapi_app
    expose:
      - 8000
    ports:
      - "8000:8000"  # Expose to local machine

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi
